#!/usr/bin/env bash

set -e

nix flake update --refresh

nixos-rebuild dry-run --flake pkgs --no-write-lock-file
sudo nixos-rebuild switch --flake pkgs --no-write-lock-file

deploy pkgs#muehml

# julia --startup-file=no update-julia.jl
